name: CI
on: 
  push:
  pull_request:
  workflow_call:
jobs:
  test_simple:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-12
          #- windows-latest
    runs-on: ${{ matrix.os }}
    env:
      CARGO_WASIX_OFFLINE: '1'
    steps:
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check out
        uses: actions/checkout@v3

      # - name: OS Setup (Ubuntu)
      #   run: |
      #     sudo apt-get update 
      #     sudo apt-get install -y build-essential curl wget xz-utils git python3

      - name: Install cargo-wasix
        shell: bash
        run: |
          cargo install --git https://github.com/wasmerio/cargo-wasix cargo-wasix

      - name: Download wasix toolchain
        shell: bash
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN  }}"
        run: |
          cargo wasix download-toolchain

      - name: Run tests
        shell: bash
        run: |
          cd simple
          cargo test

